### PR TITLE
Defer

### PR DESCRIPTION
**Pull request by ShlMlkzdh**
Add the defer calls

### CODE REVIEW

**Comment by IvBaranov** [comment]
LGTM!
Thanks for your contribution!

**Comment by ShlMlkzdh** [comment]
@IvBaranov I was thinking about making a package called `observable` and move all the code for the creation of the `Observable` objects to that package and then the `RxBluetooth` is going to be in charge of deferring these creations. This is basically what I did [here](https://github.com/ShlMlkzdh/RxSmartLock/blob/master/rx-smart-lock/src/main/java/com/shlmlkzdh/rxsmartlock/SmartLock.java). Let me know what you think.

**Comment by IvBaranov** [comment]
@ShlMlkzdh I am not sure it worth splitting the creation of the `Observable` objects in `RxBluetooth.java` for now. It is not as complicated as any of [RxSmartLock's](https://github.com/ShlMlkzdh/RxSmartLock/blob/master/rx-smart-lock/src/main/java/com/shlmlkzdh/rxsmartlock/observable/StoreCredentialObservable.java) or am I missing something?

**Comment by ShlMlkzdh** [comment]
@IvBaranov Yeah, fair enough. You're right.

**Pull request merged**
