### PR TITLE
Add connectAsServer & connectAsClient which mirror observeBluetoothSocket & observeConnectDevice but return Single.

### PR DESCRIPTION
**Pull request by vanniktech**
There's only one emission so they should be returning a Single. Decided to deprecate the old ones in order to not make any incompatible changes. If someone still needs an Observable they can use `.toObservable()` on the new methods if we ever remove the deprecated methods.

### CODE REVIEW

**Comment by vanniktech** [comment]
CI seems to be flaky:

```A problem occurred configuring root project 'RxBluetooth'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar
```

**Comment by IvBaranov** [comment]
First of all, thank you for taking your time to review and contribute.
I looked through all PRs and now I am starting to merge. Travis build passed on all of them as well.

**Comment by vanniktech** [comment]
Cheers. Thanks for the library!

**Comment by vanniktech** [comment]
Would appreciate a new release with all of the new features.

**Comment by IvBaranov** [comment]
Sure.
UPD. Release 2.0.3 is up.

**Pull request merged**
